### ISSUE TITLE
Error: Next.js has not been patched to support Next WS, please run `npx next-ws-cli@latest patch`

### ISSUE THREAD

**Issue by ziziele** [apteryxxyz/next-ws#16]
I used `npx next-ws-cli@latest patch` and followed the documentation step by step. However, even during deploying, I encountered a build error with Next.js 14.0.3. It works fine locally. Any idea what might be causing this issue?

![image](https://github.com/apteryxxyz/next-ws/assets/73204106/006a2257-fd64-43f2-a782-89cd19abed4d)

```

> Build error occurred
20:15:42.906 | Error: Next.js has not been patched to support Next WS, please run `npx next-ws-cli@latest patch`
20:15:42.906 | at Object.verifyPatch (/vercel/path0/node_modules/next-ws/server/utilities/patch.js:30:15)
20:15:42.906 | at Object.<anonymous> (/vercel/path0/next.config.js:1:27)
20:15:42.907 | at Module._compile (node:internal/modules/cjs/loader:1256:14)
20:15:42.907 | at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
20:15:42.907 | at Module.load (node:internal/modules/cjs/loader:1119:32)
20:15:42.907 | at Module._load (node:internal/modules/cjs/loader:960:12)
20:15:42.907 | at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
20:15:42.907 | at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
20:15:42.923 | Error: Command "npm run build" exited with 1
20:15:43.082

```

**Comment by apteryxxyz** [comment]
That screenshot looks like it is from Vercel build logs.
WebSocket servers (and by extension Next WS) can only be used on servers. Vercel is a serverless platform, meaning that Next WS cannot work on it.

**Comment by ziziele** [comment]
Oh, I now I get it. Thanks.
