### ISSUE TITLE
Error handling upgrade request TypeError: Cannot read properties of undefined (reading 'bind')

### ISSUE THREAD

**Issue by sharadregoti** [apteryxxyz/next-ws#27]
Getting unknow error, the client is connected and disconnected automatically and instantly.

Next JS Version: "14.1.2"

API Router Code: used the example provided
```
// app/api/ws/route.ts (can be any route file in the app directory)
export function SOCKET(
    client: import('ws').WebSocket,
    request: import('http').IncomingMessage,
    server: import('ws').WebSocketServer,
) {
    console.log('A client connected!');

    client.on('message', message => {
        client.send(message);
    });

    client.on('close', () => {
        console.log('A client disconnected!');
    });
}
```

Logs
```
 ⨯ No HTTP methods exported in '/home/sharad/personal/opencore-labs/app/api/ws/route.ts'. Export a named export for each HTTP method.
A client connected!
Error handling upgrade request TypeError: Cannot read properties of undefined (reading 'bind')
    at DevServer.handleRequestImpl (/home/sharad/personal/opencore-labs/node_modules/next/dist/server/base-server.js:461:50)
    at async /home/sharad/personal/opencore-labs/node_modules/next/dist/server/dev/next-dev-server.js:331:20
    at async Span.traceAsyncFn (/home/sharad/personal/opencore-labs/node_modules/next/dist/trace/trace.js:151:20)
    at async DevServer.handleRequest (/home/sharad/personal/opencore-labs/node_modules/next/dist/server/dev/next-dev-server.js:328:24)
    at async handleRoute (/home/sharad/personal/opencore-labs/node_modules/next/dist/server/lib/router-utils/resolve-routes.js:319:33)
    at async resolveRoutes (/home/sharad/personal/opencore-labs/node_modules/next/dist/server/lib/router-utils/resolve-routes.js:539:28)
    at async upgradeHandler (/home/sharad/personal/opencore-labs/node_modules/next/dist/server/lib/router-server.js:416:50)
    at async Server.<anonymous> (/home/sharad/personal/opencore-labs/node_modules/next/dist/server/lib/start-server.js:169:13)
A client disconnected!
 ```
 
 Patching Step
 ```
 npx next-ws-cli@latest patch
Need to install the following packages:
next-ws-cli@1.0.1
Ok to proceed? (y) y
[next-ws] Patching Next.js v14.1.2 with patch ">=13.5.1 <=14.1.4"...
[next-ws] Adding WebSocket server setup script to NextNodeServer constructor...
[next-ws] Preventing Next.js from immediately closing WebSocket connections...
[next-ws] Adding 'SOCKET' to the page module interface type...
[next-ws] Saving patch information file...
[next-ws] All done! You can now install the core Next WS package if you haven't already
```

Client Side
```
 wscat --connect ws://localhost:3000/api/ws
Connected (press CTRL+C to quit)
Disconnected (code: 1006, reason: "")
```

**Comment by apteryxxyz** [comment]
I am unable to reproduce with the `examples/basic`. Based on that stack trace it's coming from Next.js's [_res.setHeader.bind(...)](https://github.com/vercel/next.js/blob/canary/packages/next/src/server/base-server.ts#L826), and there are issues on their repo about the [same error](https://github.com/vercel/next.js/issues/56368), seemingly related to middleware. I'm under the impression that this is unrelated to Next WS.

**Comment by sharadregoti** [comment]
Yes, I am using a middleware (clerk IDP authentication).

Added my weboscket endpoint to ignore list & it started working.
```
export const config = {
    // matcher: ['/((?!.*\\..*|_next).*)', '/', '/(api|trpc)(.*)'],
    matcher: ["/",],
    ignore: ['/api/ws*'],
};
```
