### ISSUE TITLE
Nextjs 14.1.4 run build show an error: "SOCKET" is not a valid Route export field.

### ISSUE THREAD

**Issue by wangfupeng1988** [apteryxxyz/next-ws#37]
Next.js and next-ws versions below
```
"next": "14.1.4",
"next-ws": "^1.1.0",
```

I use next-ws in a `route.ts`  below

![image](https://github.com/user-attachments/assets/c6feac0c-aa7a-4354-afc2-5e13f204e6c0)

When I run dev in my local env, it's work fine, no error.

Today I deploy my project to ali-cloud serverless service, it shows an errors after next.js build 

<img width="1199" alt="image" src="https://github.com/user-attachments/assets/58efced8-ad49-4cba-babf-f138f4d3cd19">

That is my issue and thx for taking.

**Comment by apteryxxyz** [comment]
That error sounds like Next hasn't been patched, but you mention "serverless", like mentioned in the read me, Next WS cannot work in serverless environments.

**Comment by wangfupeng1988** [comment]
> but you mention "serverless", like mentioned in the read me, Next WS cannot work in serverless environments.

I ignored this tip, I see that now, thx.

---

I got another question, when I try to run the patch command `npx next-ws-cli@latest patch` in my prod environment, before next.js build . It occur another error `content.replaceAll is not a function` 

```
Run `npm audit` for details.
npm notice 
npm notice New minor version of npm available! 10.1.0 -> 10.8.2
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.8.2>
npm notice Run `npm install -g npm@10.8.2` to update!
npm notice 
npx: installed 57 in 11.951s
(node:220) UnhandledPromiseRejectionWarning: TypeError: content.replaceAll is not a function
    at line (/root/.npm/_npx/220/lib/node_modules/next-ws-cli/dist/program.cjs:69:18)
    at Object.info (/root/.npm/_npx/220/lib/node_modules/next-ws-cli/dist/program.cjs:78:57)
    at Command.<anonymous> (/root/.npm/_npx/220/lib/node_modules/next-ws-cli/dist/program.cjs:289:146)
    at Command.listener [as _actionHandler] (/root/.npm/_npx/220/lib/node_modules/next-ws-cli/node_modules/commander/lib/command.js:542:17)
    at /root/.npm/_npx/220/lib/node_modules/next-ws-cli/node_modules/commander/lib/command.js:1502:14
    at Command._chainOrCall (/root/.npm/_npx/220/lib/node_modules/next-ws-cli/node_modules/commander/lib/command.js:1386:12)
    at Command._parseCommand (/root/.npm/_npx/220/lib/node_modules/next-ws-cli/node_modules/commander/lib/command.js:1501:27)
    at /root/.npm/_npx/220/lib/node_modules/next-ws-cli/node_modules/commander/lib/command.js:1265:27
    at Command._chainOrCall (/root/.npm/_npx/220/lib/node_modules/next-ws-cli/node_modules/commander/lib/command.js:1386:12)
    at Command._dispatchSubcommand (/root/.npm/_npx/220/lib/node_modules/next-ws-cli/node_modules/commander/lib/command.js:1261:25)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:220) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:220) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

> huashuiai-web@0.1.0 build
> next build

Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry

   ▲ Next.js 14.1.4
   - Environments: .env

   Creating an optimized production build ...
 ✓ Compiled successfully
   Linting and checking validity of types ...
Failed to compile.

src/app/api/doc/collaborate/route.ts
Type error: Route "src/app/api/doc/collaborate/route.ts" does not match the required types of a Next.js Route.
  "SOCKET" is not a valid Route export field.

✖ [framework] failed to [deploy] (74.96s)
 
✖ [framework] pre-action failed to [deploy]:
====================
Error Message:
Failed to compile.
```

I exec this command `npx next-ws-cli@latest patch` in my local env, everything is OK.

Is the serverless env cause this error? 

Thx a lot.

**Comment by apteryxxyz** [comment]
> content.replaceAll is not a function

The version of Node.js is outdated.

**Comment by wangfupeng1988** [comment]
I specify Node.js version `v20` then it builds successful.

But the websocket is not connected, I handling on it. 

Thx anyway.
